# ===============================
# DATABASE (PostgreSQL - Render)
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# LOGGING
# ===============================
<<<<<<< HEAD
logging.level.org.hibernate.SQL=WARN
=======
logging.level.org.hibernate.SQL=WARN
>>>>>>> 22694b11a779a8ea9e9c67fdc6548bc4f736c207
