# =========================
# DATABASE (RENDER POSTGRES)
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d7lktfdckfvc73ac8rs0-a:5432/inventory_nqrt
spring.datasource.username=inventory_nqrt_user
spring.datasource.password=vtTPuZDwRNQHmtoVDxgXXxpSoMrptL4r
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# THYMELEAF
# =========================
spring.thymeleaf.cache=false

# =========================
# SERVER
# =========================
server.port=${PORT:8080}