spring.datasource.url=jdbc:postgresql://dpg-d7lktfdckfvc73ac8rs0-a:5432/inventory_nqrt
spring.datasource.username=inventory_nqrt_user
spring.datasource.password=vtTPuZDwRNQHmtoVDxgXXxpSoMrptL4r
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
